# Generated by Django 2.0.7 on 2018-07-26 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoes', '0003_auto_20180726_0555'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPurchased', models.IntegerField(blank=True)),
                ('time', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.Shoes')),
            ],
        ),
    ]
