# Generated by Django 2.0.7 on 2018-07-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='shoe',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='customerName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='shoeName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
