# Generated by Django 2.0.7 on 2018-07-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
